name: ai_sdk_client
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  dio: ^5.8.0+1
  lints: ^5.0.0
  test: ^1.24.0
