name: ai_sdk_client
description: A Dart library for consuming vercel AI SDK compatible data streams
version: 1.0.1
repository: https://github.com/phantomknight287/ai_sdk_client

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  dio: ^5.8.0+1
  lints: ^5.0.0
  test: ^1.24.0
